name: .NET Test

on:
  push:
    branches:
    - "develop"
  pull_request:
    branches:
    - "develop"
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute unit tests
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet test -c Release --logger "junit,LogFilePath=reports/tests.xml"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        path: reports/tests.xml
        reporter: java-junit
