name: .NET Test

on:
  push:
    branches:
    - "develop"
  pull_request:
    branches:
    - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: |
        dotnet test -c Release --collect:"XPlat Code Coverage" --logger "junit;LogFilePath=../reports/test-results.xml"
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: test-results
        path: reports/*.xml
        reporter: java-junit

    - name: Run unit tests with coverage
      run: |
        dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/lcov.info
      
    - name: Set Coverage Threshold as Environment Variable
      run: echo "COVERAGE_THRESHOLD=${{ secrets.COVERAGE_THRESHOLD }}" >> $GITHUB_ENV

    - name: Check Coverage
      shell: pwsh
      run: |
        .\scripts\check-coverage.ps1